spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
  #        jdbc:
#          lob:
#            non_contextual_creation: true
  jackson:
    serialization:
      indent-output: true
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: true

  security:
    user:
      name: user
      password: ${SPRING_SECURITY_USER_PASSWORD}
feddit:
  app:
    jwtExpirationMs: 86400000
    admin_password: ${FEDDIT_ADMIN_PASSWORD}
management:
  endpoints:
    web:
      exposure:
        include: "*"