#spring

#spring.datasource
spring.datasource.url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username: ${POSTGRES_USER}
spring.datasource.password: ${POSTGRES_PASSWORD}

#Spring.jpa
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true
spring.jpa.properties.hibernate.dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto: create-drop
# spring.jpa.show-sql: true
# spring.jpa.properties.hibernate.format_sql: true


#Spring.jackson
spring.jackson.serialization.indent-output: true
spring.jackson.default-property-inclusion: NON_NULL
spring.jackson.deserialization.fail-on-unknown-properties: true

spring.security.user.name: user
spring.security.user.password: ${SPRING_SECURITY_USER_PASSWORD}

#feddit.app
feddit.app.jwtSecret: ${FEDDIT_JWT_SECRET}
feddit.app.jwtExpirationMs: 86400000